name: Next.js CI/CD
on:
  push:
    branches:
      - staging
jobs:
  build:
    runs-on: ubuntu version 20.04
    steps:
    
    - name: Checkout code
      uses: actions/checkout@v2
    
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    
    - name: Install Packages
      run: npm install
    
    - name: Check Formatting
      run: npx prettier --check .
    
    - name: Build
      run: npm run build